# Please, rename this file to config.yml

# The streaming services used to have real-time data
# This is an array (use new lines and dashes!)
websocket-data-services:
  - wss://xxxxxxxx

# The slack integration
slack-web-hook: https://hooks.slack.com/services/XXXX/XXXXXX

# The file containing the monitored prefixes. Please see monitored_prefixes_test.yml for an example
# This is an array (use new lines and dashes!)
monitored-prefixes-files:
    - monitored_prefixes.yml


number-peers-before-alert: 5

# 10 seconds is the default
repeat-alert-after-seconds: 10

# delete or 0 for never
repeat-status-heartbeat-after-seconds: 20


# stop sending the same alert after x seconds. Default 600
reset-after-seconds: 400